import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderNavbar from "@/app/components/header-navbar";
import {AntdRegistry} from '@ant-design/nextjs-registry';
import {ConfigProvider} from "antd";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Mua Vé xem phim Online giá rẻ trên MoMo. Đặt mua ngay !",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <AntdRegistry>
            <ConfigProvider
                theme={{
                    token: {
                        colorPrimary: '#d42987',
                    },
                    components: {
                        Dropdown: {
                            controlItemBgHover: '#fef1f8'
                        }
                    }
                }}>
                <HeaderNavbar/>
                {children}
            </ConfigProvider>
        </AntdRegistry>
        </body>
        </html>
    );
}
